version: '3'

services:
  api:
    build: .
    container_name: "api"
    ports:
      - 6324:6324
    links:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_NAME=myapp
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:3.4.9
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    # ports:
    #     - 27020:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet