version: '3'

services:
  microservice:
    build: .
    container_name: "cc"
    ports:
      - 6324:6324
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_NAME=microservice1
    volumes:
      - .:/usr/src/app
  mongodb:
    image: daocloud.io/library/mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    # ports:
    #     - 27020:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet